### ISSUE TITLE
Error when executing install command

### ISSUE THREAD

**Issue by oopmarcos** [aendeavor/i3buntu#79]
Hello, I got an error when I ran the first command to start the installation.
![asd](https://user-images.githubusercontent.com/62664733/97800344-d73e6600-1c34-11eb-9465-d2b14fd0be97.png)

The system is up to data and curl, wget and rsync are installed.

**Comment by aendeavor** [comment]
This was a mistake from my side where `app` was actually the wrong name. It should be fixed by now. Can you retry?

**Comment by oopmarcos** [comment]
Works fine now. Thanks!
